export const GET_PEOPLE_DATA = 'GET_PEOPLE_DATA'

export const MAKE_ORDER = 'MAKE_ORDER'

export const SET_LOADING = 'SET_LOADING'
export const SET_ORDERING = 'SET_ORDERING'

export const SET_ERROR = 'SET_ERROR';

export const FETCH_PEOPLE_DATA = 'FETCH_PEOPLE_DATA'
export const FETCH_INFO_DATA = 'FETCH_INFO_DATA'


export const SET_CART_ITEMS = 'SET_CART_ITEMS'
export const UPDATE_CART = 'UPDATE_CART'

export const DATA_RECEIVED_INFO = 'DATA_RECEIVED_INFO'
export const DATA_RECEIVED = 'DATA_RECEIVED'
